-- Staging model for erp_orders (grain: one order; meaningful NULLs preserved for delivery/rating/return fields per non-completed orders)
with source as (
    select * from {{ source('raw', 'erp_orders') }}
),
renamed as (
    select
        order_id,
        order_date,
        order_datetime,
        order_status,
        sales_channel,
        customer_id,
        customer_name,
        customer_age,
        gender,
        customer_segment,
        customer_type,
        customer_city,
        customer_state,
        customer_country,
        region,
        customer_postal_code,
        payment_method,
        payment_status,
        currency,
        shipping_method,
        warehouse,
        cast(delivery_days as integer) as delivery_days,
        cast(estimated_delivery_days as integer) as estimated_delivery_days,
        delivery_status,
        return_status,
        return_reason,
        cast(customer_rating as numeric(2, 1)) as customer_rating,
        review_sentiment,
        customer_review,
        marketing_channel,
        campaign_name,
        coupon_code,
        loyalty_points_earned,
        loyalty_points_redeemed,
        quantity,
        cast(gross_sales as numeric(12, 2)) as gross_sales,
        cast(discount_amount as numeric(12, 2)) as discount_amount,
        cast(tax_amount as numeric(12, 2)) as tax_amount,
        cast(shipping_cost as numeric(12, 2)) as shipping_cost,
        cast(net_sales as numeric(12, 2)) as net_sales,
        cast(product_cost as numeric(12, 2)) as product_cost,
        cast(profit as numeric(12, 2)) as profit,
        cast(profit_margin_percentage as numeric(6, 2)) as profit_margin_percentage,
        cast(customer_lifetime_value as numeric(12, 2)) as customer_lifetime_value,
        is_repeat_customer,
        customer_order_count
    from source
)
select * from renamed